---
#

- name: restart {{ module }}
  shell: "su -l {{ deploy_user }} -c 'cd {{ deploy_root }}/{{ module }}/ && ./control stop ; sleep 5 && ./control start'"
  ignore_errors: yes

- name: wait {{ module }} active
  wait_for: port={{ port['http'][module] }} delay=5 timeout=60

- name: check {{ module }} status
  shell: "curl http://127.0.0.1:{{ port['http'][module] }}{{ health[module] }} |grep ok"

